---
    # This playbook contains common plays that will be run on all nodes.
    
    -   name: Install tomcat
        yum: name=tomcat state=present enabled=yes
        tags: tomcat 

    -   name: Tomcat_Webapps
        yum: name=tomcat-webapps state=present
        tags: tomcat-webapps

    -   name: Install tomcat admin webapps
        yum: name=tomcat-admin-webapps state=present
        tags: tomcat 

    -   name: Restart tomcat
        yum: name=tomcat state=restarted
        tags: tomcat 

