---
    # This playbook contains common plays that will be run on all nodes.
    
    -   name: Install tomcat
        yum: name=tomcat state=present
        tags: tomcat 

    -   name: Tomcat_Webapps
        yum: name=tomcat-webapps state=present
        tags: tomcat-webapps

    -   name: Install tomcat admin webapps
        yum: name=tomcat-admin-webapps state=present
        tags: tomcat 

    -   template: src="tomcat-users.xml" dest="/usr/share/tomcat/conf/tomcat-users.xml"
        tags: tomcat users

    -   name: Restart tomcat
        service: name=tomcat state=restarted enabled=yes
        tags: tomcat 

